### ISSUE TITLE
VOLUME prevents build-time caching?

### ISSUE THREAD

**Issue by bbc2** [niaquinto/docker-gradle#13]
In the Dockerfile:

``` dockerfile
VOLUME ["/root/.gradle/caches", "/usr/bin/app"]
```

Unless `/root/.gradle/caches` is mounted on the host, it seems to me that any cache generated by a `RUN gradle ...` will be discarded, which prevents easy caching of downloaded dependencies for instance.  Wouldn't it be better if the user could choose what to consider as a volume?

**Comment by JosephEarl** [comment]
You can use any path on the host, `/root/.gradle/caches` is the path in the container.
For instance `docker run -v mycache:/root/.gradle/caches niaquinto/gradle` using the `mycache` folder on the host.

**Comment by niaquinto** [comment]
Thanks Joeseph for clearing this up. I'm going to close this issue.

**Comment by bbc2** [comment]
Thank you for the explanations but that's not solving the issue, albeit a minor one. I did say you could mount the directory on the host but that's not what you always want.  Sometimes you just want the directory to be inside the image itself (in my case for cached CI builds).  This is prevented by the `VOLUME` command here and you can't revert it as far as I know.  My point is it would be better for the user to be able to choose whether to have `/root/.gradle/caches` in the image, in the host, or in a volume.

That's not a big issue though.  And for those looking for an alternative, you can use `gradle wrapper`, add the wrapper to your regular image and be done with it.  Gradle makes it quite easy thankfully.

**Comment by niaquinto** [comment]
@bbc2 How are you running the container?

When I created this, it was because I only wanted Docker installed on one particular machine. So, I symlinked a short script that just runs the container w/ whatever arguments and cleaned up afterwards.

```
docker run --rm -it -v /tmp/gradle-caches:/root/.gradle/caches niaquinto/gradle --help
```

Off the top of my head, I'm not thinking of a reason to run this without `--rm`. Am I totally off-base with that? Given `--rm`, it doesn't matter if `/root/.gradle/caches` is a volume or not, because the container is deleted after each run. But as long as you mount the volume to the host, you shouldn't have any issues.

**Comment by bbc2** [comment]
The way my CI works, the application is built as part of the creation of the image, then the tests are run in a container based on that image. The Dockerfile looks like this:
```dockerfile
COPY build.gradle .
RUN gradle resolveDependencies
COPY . .
RUN gradle build
```
The dependencies are thus only installed when `build.gradle` changes.  Otherwise, the CI reuses the existing image layer for that. After the image is built, it is run with something like:
```bash
docker run -t my-image ./ci/tests.sh
```
or
```bash
docker run -t my-image ./ci/deploy.sh
```
If `VOLUME /root/.gradle/caches` is used, dependencies are re-downloaded at each `docker run`. Unless of course you mount it somewhere on your host to preserve them, like you do with `-v /tmp/gradle-caches`.  Unfortunately, I'm not keen on mounting host directories on my CI server. I'd rather only manage Docker and nothing else.

Does this use-case make sense to you?

**Comment by niaquinto** [comment]
Absolutely, that makes sense. I can sympathize with not wanting to have stuff on the host; that's why I created this image in the first place!

Ok so to summarize, including the `VOLUME` declaration in the container means that when your image (based off it) puts something in `/root/.gradle/caches`, it doesn't get commit'ed with the rest of the container (as mentioned in the first note (here)[https://docs.docker.com/engine/reference/builder/#volume]).

The question now is whether removing it will break other people's builds / images.

It seems to me that the only use of having the `VOLUME` mentioned in the image explicitly is for the `--volumes-from` option to include volumes from one container into another. That's kinda an odd use case I think for this container. But, these people will still be able to get that functionality by adding a `VOLUME` declaration to their Dockerfile or by using `-v` at runtime. They'll just have to update it, because wouldn't be default anymore.

Another ramification of changing this would be that people that aren't paying attention will have larger images, because dependencies will get committed. These people will have to do `rm -rf ${HOME}/.gradle` if they want to get rid of this.

So it seems that adding this is a good deal. You (and other people with your use case) get to use it how you want and other people that were relying on that behavior can just update their images/run command to include the volume.

I'm not too worried about breaking peoples' builds because they should really be using the `-v` option at runtime. Hopefully we don't get angry people with broken builds!

**Comment by niaquinto** [comment]
I've removed the `VOLUME` declaration from the Dockerfile for latest and 3.3. And, I've added [a section in the README](https://github.com/niaquinto/docker-gradle/tree/3.3) about caching.

**Comment by bbc2** [comment]
Nice!  The `resolveDependencies` command I referred to isn't in Gradle by default.  I copied it from https://jdpgrailsdev.github.io/blog/2014/10/28/gradle_resolve_all_dependencies.html.
